[bans]
multiple-versions = "allow"

[licenses]
allow = [
    "MIT",
]

[licenses.private]
ignore = true

[sources]  
unknown-git = "deny"  
  
[sources.allow-org]  
github = ["Weichwerke-Heidrich-Software"]
